-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgKAurASmQkZI8CAjQ
NV0AGaOmD/+ieNtkSjmHrrCspAygCgYIKoZIzj0DAQehRANCAAQNaWtolLZeNMT2
KWsuBP7OMhU6IqLWz01kY2ZkOo2o26CgOpbXXMNkCAxu4zMMtcVHiLYgP4YtLGOW
1/+zl3an
-----END PRIVATE KEY-----